services:
  traefik:
    image: traefik:${infra__traefik_version:-v2.11}
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # EntryPoints
      - "--entrypoints.web.address=:80"
      # Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # Allow self-signed certs on backends
      - "--serversTransport.insecureSkipVerify=true"
    environment:
      - DOCKER_API_VERSION=1.44

    ports:
      - "${infra__traefik_http_port:-80}:80"                     # Public (used by Cloudflare Tunnel)
      - "${infra__local_bind_ip:-127.0.0.1}:${infra__traefik_dashboard_port:-8080}:8080"       # Traefik dashboard (LOCAL ONLY)

    volumes:
      - ${infra__docker_socket:-/var/run/docker.sock}:/var/run/docker.sock:ro

    networks:
      - proxy

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock

    ports:
      - "${infra__local_bind_ip:-0.0.0.0}:${infra__portainer_port:-9000}:9000"       # Portainer UI (accessible via tailscale)

    volumes:
      - ${infra__docker_socket:-/var/run/docker.sock}:/var/run/docker.sock
      - portainer_data:/data

    networks:
      - proxy

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    profiles:
      - cloudflare
    restart: unless-stopped
    depends_on:
      - traefik
    command: tunnel --no-autoupdate run --token ${infra__cf_tunnel_token}

    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  portainer_data:
