version: "3.9"

services:
  word-mastermind:
    image: ghcr.io/clupasq/word-mastermind:latest
    container_name: word-mastermind
    restart: unless-stopped

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordmastermind.rule=Host(`wordmastermind.jaypussy.site`)"
      - "traefik.http.services.wordmastermind.loadbalancer.server.port=80"

networks:
  proxy:
    external: true

