services:
  word-mastermind:
    image: ghcr.io/clupasq/word-mastermind:latest
    container_name: word-mastermind
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordmastermind.rule=Host(`wordmastermind.${shared__base_domain:-jaypussy.site}`)"
      - "traefik.http.routers.wordmastermind.entrypoints=web"
      - "traefik.http.services.wordmastermind.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
