services:
  jaypussy-site:
    image: nginx:alpine
    container_name: jaypussy-site
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./site:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaypussy-site.rule=Host(`${shared__base_domain:-jaypussy.site}`)"
      - "traefik.http.routers.jaypussy-site.entrypoints=web"
      - "traefik.http.services.jaypussy-site.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
