services:
  dev:
    build:
      context: .
      args:
        GIT_USER_NAME: ${dev_env__git_user_name:-Developer}
        GIT_USER_EMAIL: ${dev_env__git_user_email:-dev@localhost}
    image: node-dev-env
    container_name: node-dev
    stdin_open: true
    tty: true
    environment:
      - GITHUB_USER=${dev_env__github_user:-}
      - GITHUB_PAT=${dev_env__github_pat:-}
      - ANTHROPIC_API_KEY=${dev_env__anthropic_api_key:-}
      - VERCEL_TOKEN=${dev_env__vercel_token:-}
      - DOCKER_HOST=tcp://dind:2375
    volumes:
      - ./workspace:/app
    working_dir: /app
    networks:
      - dev-internal
    depends_on:
      - dind

  dind:
    image: docker:27-dind
    container_name: dev-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - dind-data:/var/lib/docker
    networks:
      - dev-internal

  dev-proxy:
    image: nginx:alpine
    container_name: dev-proxy
    depends_on:
      - dind
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
      - dev-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev.rule=Host(`dev.${shared__base_domain:-jaypussy.site}`)"
      - "traefik.http.routers.dev.entrypoints=web"
      - "traefik.http.routers.dev.service=dev"
      - "traefik.http.services.dev.loadbalancer.server.port=3000"
      - "traefik.http.routers.dev2.rule=Host(`dev2.${shared__base_domain:-jaypussy.site}`)"
      - "traefik.http.routers.dev2.entrypoints=web"
      - "traefik.http.routers.dev2.service=dev2"
      - "traefik.http.services.dev2.loadbalancer.server.port=3001"
      - "traefik.http.routers.oc.rule=Host(`oc.${shared__base_domain:-jaypussy.site}`)"
      - "traefik.http.routers.oc.entrypoints=web"
      - "traefik.http.routers.oc.service=oc"
      - "traefik.http.services.oc.loadbalancer.server.port=4096"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
  dev-internal:
    driver: bridge

volumes:
  dind-data:
